- name: install php
  user: ubuntu
  hosts: lampstack
  become: True
  become_user: root
  gather_facts: True
  vars_files:
    - ../vars/default.yml
  tasks:
    - name: "Install software-properties-common"
      package: name=software-properties-common state=present
  
    - name: Add repository for PHP versions (Ubuntu).
      apt_repository: repo='ppa:ondrej/php'

    - name: "Install php {{PHP_VER}}"
      package: name=php{{PHP_VER}} state=present

    - name: "Install php{{PHP_VER}}-common"
      package: name=php{{PHP_VER}}-common state=present
      
    - name: "Install php{{PHP_VER}}-mysql"
      package: name=php{{PHP_VER}}-mysql state=present

    - name: "Install php{{PHP_VER}}-curl"
      package: name=php{{PHP_VER}}-curl state=present

    - name: "Install php{{PHP_VER}}-json"
      package: name=php{{PHP_VER}}-json state=present

    - name: "Install php{{PHP_VER}}-mbstring"
      package: name=php{{PHP_VER}}-mbstring state=present

    - name: "Install php{{PHP_VER}}-xml"
      package: name=php{{PHP_VER}}-xml state=present

    - name: Install php{{PHP_VER}}-zip"
      package: name=php{{PHP_VER}}-zip state=present

    - name: "Install php{{PHP_VER}}-gd"
      package: name=php{{PHP_VER}}-gd state=present

    - name: "Install php{{PHP_VER}}-soap"
      package: name=php{{PHP_VER}}-soap state=present

    - name: "Install php{{PHP_VER}}-ssh2"
      package: name=php{{PHP_VER}}-ssh2 state=present

    - name: "Install php{{PHP_VER}}-tokenizer"
      package: name=php{{PHP_VER}}-tokenizer state=present

