- name: install php
  user: ubuntu
  hosts: lampstack
  become: True
  become_user: root
  gather_facts: True
  tasks: 
    - name: "remove existing php7.2"
      package: name=php7.2 state=absent

    - name: "disable php 7.2 mod"
      ansible.builtin.shell: a2dismod php7.2

    - name: "Install software-properties-common"
      package: name=software-properties-common state=present
  
    - name: Add repository for PHP versions (Ubuntu).
      apt_repository: repo='ppa:ondrej/php'

    - name: "Install php7.4"
      package: name=php7.4 state=present

    - name: "Install php7.4-common"
      package: name=php7.4-common state=present
      
    - name: "Install php7.4-mysql"
      package: name=php7.4-mysql state=present

    - name: "Install php7.4-curl"
      package: name=php7.4-curl state=present

    - name: "Install php7.4-json"
      package: name=php7.4-json state=present

    - name: "Install php7.4-mbstring"
      package: name=php7.4-mbstring state=present

    - name: "Install php7.4-xml"
      package: name=php7.4-xml state=present

    - name: Install php7.4-zip"
      package: name=php7.4-zip state=present

    - name: "Install php7.4-gd"
      package: name=php7.4-gd state=present

    - name: "Install php7.4-soap"
      package: name=php7.4-soap state=present

    - name: "Install php7.4-ssh2"
      package: name=php7.4-ssh2 state=present

    - name: "Install php7.4-tokenizer"
      package: name=php7.4-tokenizer state=present

    - name: "enable php 7.4 mod"
      ansible.builtin.shell: a2dismod php7.4
